# Generated by Django 3.1.7 on 2021-03-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_creacion',
            field=models.DateField(default=None, null=True),
        ),
    ]
