# Generated by Django 3.1.7 on 2021-03-19 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('username_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Esta_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canciones.cancion')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('username_usuario', 'nombre'), name='playlist unica'),
        ),
        migrations.AddConstraint(
            model_name='esta_en',
            constraint=models.UniqueConstraint(fields=('id_playlist', 'id_cancion'), name='cancion unica en playlist'),
        ),
    ]
