# Generated by Django 3.1.7 on 2021-03-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='link',
            field=models.URLField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
